export const USER_REGISTRATION_FAILED = "USER_REGISTRATION_FAILED";

export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const LOGOUT_FAILED = "LOGOUT_FAILED";
